type User {
    username: String!
}

input signUpUser {
    username: String!
    email: String!
    password: String!
}

input logInUser {
    identity: String!
    password: String!
}

input forgotPasswordUser {
    identity: String!
}

input resetPasswordUser {
    resetToken: String!
    password: String!
}

input updatePasswordUser {
    currentPassword: String!
    newPassword: String!
}
