#!/bin/bash

function createOrg() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/judicature.com/
  local PEER=$1

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/judicature.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-judicature --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-judicature.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-judicature.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-judicature.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-judicature.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/judicature.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy judicature's CA cert to judicature's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/judicature.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem" "${PWD}/organizations/peerOrganizations/judicature.com/msp/tlscacerts/ca.crt"

  # Copy judicature's CA cert to judicature's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/judicature.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem" "${PWD}/organizations/peerOrganizations/judicature.com/tlsca/tlsca.judicature.com-cert.pem"

  # Copy judicature's CA cert to judicature's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/judicature.com/ca"
  cp "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem" "${PWD}/organizations/peerOrganizations/judicature.com/ca/ca.judicature.com-cert.pem"

  infoln "Registering peer${PEER}"
  set -x
  fabric-ca-client register --caname ca-judicature --id.name peer${PEER} --id.secret peer${PEER}pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-judicature --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-judicature --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer${PEER} msp"
  set -x
  fabric-ca-client enroll -u https://peer${PEER}:peer${PEER}pw@localhost:7054 --caname ca-judicature -M "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/judicature.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/msp/config.yaml"

  infoln "Generating the peer${PEER}-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer${PEER}:peer${PEER}pw@localhost:7054 --caname ca-judicature -M "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/tls" --enrollment.profile tls --csr.hosts peer${PEER}.judicature.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/judicature.com/peers/peer${PEER}.judicature.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-judicature -M "${PWD}/organizations/peerOrganizations/judicature.com/users/User1@judicature.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/judicature.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/judicature.com/users/User1@judicature.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://org1admin:org1adminpw@localhost:7054 --caname ca-judicature -M "${PWD}/organizations/peerOrganizations/judicature.com/users/Admin@judicature.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/judicature/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/judicature.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/judicature.com/users/Admin@judicature.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/judicature.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/judicature.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/judicature.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/judicature.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/judicature.com/msp/tlscacerts/tlsca.judicature.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/judicature.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/judicature.com/tlsca/tlsca.judicature.com-cert.pem"

  infoln "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/judicature.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls" --enrollment.profile tls --csr.hosts orderer.judicature.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/judicature.com/orderers/orderer.judicature.com/msp/tlscacerts/tlsca.judicature.com-cert.pem"

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/judicature.com/users/Admin@judicature.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/judicature.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/judicature.com/users/Admin@judicature.com/msp/config.yaml"
}
